---
- name: Install common packages
  apt: pkg={{item}} state=latest update_cache=yes
  with_items:
      - unzip
      - nodejs
      - npm
      - ruby

- name: Find path to nodejs
  command: which nodejs
  register: nodejs_path

- name: symlink the nodejs executable to node
  command: "ln -sf {{ item }} /usr/bin/node"
  with_items: nodejs_path.stdout

- name: Install PHP and its modules
  apt: pkg={{ item }} state=latest
  with_items:
    - php5
    - php5-cli
    - php5-curl
    - php5-gd
    - php5-imagick
    - php5-mysql
    - php5-xmlrpc
    - php5-xdebug

- name: Install Apache and its modules
  apt: pkg={{ item }} state=latest
  with_items:
    - apache2
    - libapache2-mod-php5

- name: download wp-cli
  get_url: url=https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar dest=/usr/local/bin/wp

- name: update permissions of wp-cli to allow anyone to execute it (should be only for local install!)
  file: path=/usr/local/bin/wp mode="0755"

- name: Activate mod_rewrite
  apache2_module: 
    name: rewrite
    state: present